# -*- coding: utf-8 -*-
"""RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp7o0ZID1e4ZRezGbJRuW-CIBVC-DDTl
"""



import time
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from google.colab import drive

# ---- 1. Mount Google Drive ----
drive.mount('/content/drive')

# ---- 2. Load Dataset ----
train_path = "/content/drive/My Drive/Dataset/Train_set.csv"
test_path = "/content/drive/My Drive/Dataset/Test_set.csv"
val_path = "/content/drive/My Drive/Dataset/Validation_set.csv"

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)
val_df = pd.read_csv(val_path)

# ---- 3. Preprocess Data ----
X_train, y_train = train_df.drop(columns=["type"]).values, train_df["type"].values
X_test, y_test = test_df.drop(columns=["type"]).values, test_df["type"].values
X_val, y_val = val_df.drop(columns=["type"]).values, val_df["type"].values

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val = scaler.transform(X_val)

# Convert labels to float32 for TensorFlow compatibility
y_train = np.array(y_train, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)
y_val = np.array(y_val, dtype=np.float32)

# Reshape data for RNN input (samples, timesteps, features)
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
X_val = X_val.reshape(X_val.shape[0], 1, X_val.shape[1])

# ---- 4. Build RNN Model ----
rnn_model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(1, X_train.shape[2])),
    Dropout(0.5),
    LSTM(32),
    Dropout(0.5),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')  # Binary classification
])

# Compile the model
rnn_model.compile(optimizer=Adam(learning_rate=0.0005),
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

# Early stopping to prevent overfitting
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# ---- 5. Train the Model ----
train_start_time = time.time()

history_rnn = rnn_model.fit(X_train, y_train,
                            epochs=5,
                            batch_size=64,
                            validation_data=(X_val, y_val),
                            callbacks=[early_stop])

train_end_time = time.time()
print(f"\nTraining Time: {train_end_time - train_start_time:.2f} seconds")

# ---- 6. Evaluate the Model ----
test_start_time = time.time()

rnn_loss, rnn_accuracy = rnn_model.evaluate(X_test, y_test)

test_end_time = time.time()
print(f"Testing Time: {test_end_time - test_start_time:.2f} seconds")

print(f"RNN Test Accuracy: {rnn_accuracy * 100:.2f}%")

# ---- 7. Compute Precision, Recall, F1-Score ----
# Generate predictions
y_pred_prob = rnn_model.predict(X_test)
y_pred_labels = (y_pred_prob > 0.5).astype(int).flatten()
y_test = y_test.astype(int)

precision = precision_score(y_test, y_pred_labels)
recall = recall_score(y_test, y_pred_labels)
f1 = f1_score(y_test, y_pred_labels)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

# Confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_labels).ravel()

false_alarm_rate = fp / (fp + tn)
missed_detection_rate = fn / (fn + tp)

print(f"False Alarm Rate (FAR): {false_alarm_rate:.4f}")
print(f"Missed Detection Rate (MDR): {missed_detection_rate:.4f}")

# ---- 8. Plot Training History ----
plt.figure(figsize=(10, 5))
plt.plot(history_rnn.history['accuracy'], label='Train Accuracy')
plt.plot(history_rnn.history['val_accuracy'], label='Validation Accuracy')
plt.title('RNN Model Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()